#Workflow that creates a new package on any new release or when manually triggered
name: Release Frontend Jar
on:
    push:
        tags:
            - v[0-9]+\.[0-9]+\.[0-9]+.* # this is temp

jobs:
    build_package:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Parse provided version tag
              # Parse the input version tag (from the tag push) and store it in an environment variable
              run: |
                  # Removes the v in the ref name == vX.Y.Z
                  VERSION="${GITHUB_REF_NAME#v}"
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Setup JDK 25 # Java -v >= 25.0.1
              uses: actions/setup-java@v4 # Creates a settings.xml
              with:
                java-version: "25"
                distribution: "temurin"
                cache: "maven"
                server-id: github # Value of the server id field of the pom.xml
                server-username: ${{ github.actor }}
                server-password: ${{ secrets.GH_PACKAGES_TOKEN_TEST }}
                settings-path: ${{ github.workspace }} # location for the settings.xml file

            - name: Set the Maven Version
              run: |
                  mvn versions:set -DnewVersion=$VERSION 
                  mvn versions:commit

            - name: Build Maven Package
              run: mvn --batch-mode package --file pom.xml --settings ${{ github.workspace }}/settings.xml

            - name: publish the package to github packages
              run: mvn deploy --settings ${{ github.workspace }}/settings.xml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
