#Workflow that creates a new package on any new release or when manually triggered
name: Release Frontend Jar and Build Docker Image

on:
  push:
   tags:
     - release # push a tag called release to release a workflow, single-source-of truth of version is in pom
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: doda2025-team22/app
  BUILD_ID: latest

jobs:
  build_package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 25 # Java -v >= 25.0.1
        uses: actions/setup-java@v4 # Creates a settings.xml
        with:
          java-version: "25"
          distribution: "temurin"
          server-id: "github" # must match <id> in distributionManagement
          server-username: MAVEN_USERNAME # env var names, not values
          server-password: MAVEN_PASSWORD

      - name: Delete original Tag
        run: git push --delete origin ${GITHUB_REF#refs/tags/} #since the worklow only triggers with a tag, this should, in theory, not break

      - name: Build & deploy
        run: mvn -B deploy
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  build_container:
    runs-on: ubuntu-latest
    needs: build_package
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup JDK 25 # Java -v >= 25.0.1
        uses: actions/setup-java@v4 # Creates a settings.xml
        with:
          java-version: "25"
          distribution: "temurin"
          server-id: "github" # must match <id> in distributionManagement
          server-username: MAVEN_USERNAME # env var names, not values
          server-password: MAVEN_PASSWORD

      - name: Parse version from tag
        id: version
        run: |
          VERSION_SUFFIX=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          VERSION=$(echo "$VERSION_SUFFIX" | sed 's/-.*//')
          MAJOR=$(echo "$VERSION" | cut -d . -f 1)
          MINOR=$(echo "$VERSION" | cut -d . -f 2)
          PATCH=$(echo "$VERSION" | cut -d . -f 3)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "VERSION_MINOR=$MINOR" >> $GITHUB_ENV
          echo "VERSION_PATCH=$PATCH" >> $GITHUB_ENV
        env:
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Log version
        run: |
          echo "Building version ${{ env.VERSION }}"
          echo "Major: ${{ env.VERSION_MAJOR }}, Minor: ${{ env.VERSION_MINOR }}, Patch: ${{ env.VERSION_PATCH }}"

      - name: Log in ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            FRONTEND_PORT=8081
            MODEL_HOST=http://127.0.0.1:8081
            VERSION=${{ env.VERSION }}
            GH_ACTOR=${{ github.actor }}
            GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_MAJOR }}.${{ env.VERSION_MINOR }}.${{env.BUILD_ID}}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION_MAJOR }}.${{env.BUILD_ID}}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{env.BUILD_ID}}
